### ISSUE TITLE
Leaderboards don't work on all levels

### ISSUE THREAD

**Issue by Wkymys** [PhantasarProductions/cynthia#56] opened 2017-12-19 12:19 UTC
Leaderbord won't update after some levels (like The Leprechaun Field).

**Comment by Tricky1975** [comment] 2017-12-19 12:38
I shall try to sort this out. It might possibly be fixed  already, but I'll try to dig through the logs to make sure. ;)

**Comment by Tricky1975** [comment] 2017-12-19 15:39
I've checked the logs and nothing odd shows up. Maybe you were victim of Anna's overagressive behavior that I already fixed. (Anna is my security bot on the leaderboards). 
Can you try it again, and tell me if the issue still persists?

**Comment by Wkymys** [comment] 2017-12-20 11:52
Well, the problem only happens on a few specific levels. I finished this level, and the Puzzle Solved screen does not show any results, and neither do the Leaderboard.
I saw that Anna reseted the Leaderbord, but the other levels are updating the scores correctly.

**Comment by Tricky1975** [comment] 2017-12-20 16:24
I see two things in Anna's log that look a bit strange.
Anna has performed to bans that are not properly motivated, I really hope you are not one of them. Can you tell me which name you entered in the game when Cynthia asked your name? Anna uses this name for the leaderboards after all, and I do find this name in Anna's logs, so that helps me to confirm or deny any possibility.

**Comment by Wkymys** [comment] 2017-12-21 11:38
I just replayed Egypt levels, and Leaderboard appear normally.
But after I play the "The Leprechaun Field", for example, the Puzzle Solved screen shows no names.
![ps1](https://user-images.githubusercontent.com/34680949/34254298-9eaf9902-e632-11e7-9e57-e6a34b712df5.png)

**Comment by Tricky1975** [comment] 2017-12-21 12:54
Now that's odd, indeed.... I guess a little investigation is in order.
Well, I shall put in these scores manually... THIS TIME ;)

**Comment by Wkymys** [comment] 2017-12-21 13:27
Hahaha don't worry!
Ya can count on me to try again the level once the mystery is solved!
I think that this leaderboard issue is happening on all Ireland levels, and only on them. I tried another level on Greece and saw no problem.

**Comment by Tricky1975** [comment] 2017-12-21 16:54
I think I may have found the the course of the issue. It may be a "client-side" bug...
Did you change realms in one session?
Like playing both Ireland and Egypt in without restarting the game?
And did you restart the game before you started on Greece?
I think the realm change might be the source of all evil, but I didn't yet have the time to try this out.

**Comment by Tricky1975** [comment] 2017-12-21 17:55
I've tried to replicate this bug, but everything works to me.
I did see something else in the database which might have confused Anna, but which I am not going to discuss out in the open (for obvious reasons) in a public issue tracker. It could be coincidence this caused Anna to malfunction on the Ireland puzzles.... I wonder...

**Comment by Wkymys** [comment] 2017-12-22 12:05
I tried again those levels, and the leaderboards are working perfectly now.
Maybe it was my pc needing a reset, or maybe Anna understood the problem!

**Comment by Tricky1975** [comment] 2017-12-22 13:09
Okay... then I shall close this issue.
You can still send in a reply to it if troubles still rise up. 😉 
I hope you can forgive Anna. She may be a bot, but she's rather sensitive. ;)

**Closed as completed by Tricky1975** 2017-12-22 13:09 UTC
Labels: Net: Anna, Awaiting feedback

**Comment by Tricky1975** [comment] 2018-04-20 13:32
I found out this issue could be caused by a little database error caused during automated maintenance Anna always does at least once each 24 hours... This SHOULD be fixed now... If not, let me know...
